data_path: data/
experiment_data_path: data/experiments/
experiments_integration: integration
experiments_integration_version: 2
latest_experiments_version:
  after_integration: # train 기준으로 만
    3: 3.0.3
  before_integration: # train 기준으로 만
    0: 0.0.3
    1: 1.0.2
latest_test_version: 1.0.2
latest_train_version: 2.0.1
latest_valid_version: 2.0.1
