data_path: data/
experiment_data_path: data/experiments/
experiments_integration: integration
latest_experiments_version:
  0: 0.0.3
  1: 1.0.3
latest_test_version: 1.0.2
latest_train_version: 2.0.1
latest_valid_version: 2.0.1
